# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b95734f69c9ad9ad69467be5d9c1f2bdeb5facdae07f7a61041a470191b16396fcbbaa7b3b410a40bea80123f4e3c8199c973596d203667833c45c712a3e97ec

test:
  secret_key_base: 50d64e9a50192ac0cb2b08599306da998c011e2590da628d5bf04ee4aa172bddf8ae1a07661e3ca63947fb4a14134c76170e1d25603df627e231c085be3dc01b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
